name: WebHostMost Login

on:
  schedule:
    - cron: '0 0 20 * *'  # 每月20号UTC0点（北京时间早8点）
  workflow_dispatch:       # 允许手动运行

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install puppeteer@latest

      - name: Run login script
        env:
          USERNAME_AND_PASSWORD: ${{ secrets.USERNAME_AND_PASSWORD }}
        run: node scripts/login.js
